/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as PaywallIdRouteImport } from './routes/paywall.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AnalyzingIdRouteImport } from './routes/analyzing.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallIdRoute = PaywallIdRouteImport.update({
  id: '/paywall/$id',
  path: '/paywall/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingIdRoute = AnalyzingIdRouteImport.update({
  id: '/analyzing/$id',
  path: '/analyzing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/analyzing/$id': typeof AnalyzingIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/paywall/$id': typeof PaywallIdRoute
  '/report/$id': typeof ReportIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/analyzing/$id': typeof AnalyzingIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/paywall/$id': typeof PaywallIdRoute
  '/report/$id': typeof ReportIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/analyzing/$id': typeof AnalyzingIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/paywall/$id': typeof PaywallIdRoute
  '/report/$id': typeof ReportIdRoute
  '/results/$id': typeof ResultsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upload'
    | '/analyzing/$id'
    | '/checkout/return'
    | '/paywall/$id'
    | '/report/$id'
    | '/results/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/analyzing/$id'
    | '/checkout/return'
    | '/paywall/$id'
    | '/report/$id'
    | '/results/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/upload'
    | '/analyzing/$id'
    | '/checkout/return'
    | '/paywall/$id'
    | '/report/$id'
    | '/results/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadRoute: typeof UploadRoute
  AnalyzingIdRoute: typeof AnalyzingIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  PaywallIdRoute: typeof PaywallIdRoute
  ReportIdRoute: typeof ReportIdRoute
  ResultsIdRoute: typeof ResultsIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall/$id': {
      id: '/paywall/$id'
      path: '/paywall/$id'
      fullPath: '/paywall/$id'
      preLoaderRoute: typeof PaywallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing/$id': {
      id: '/analyzing/$id'
      path: '/analyzing/$id'
      fullPath: '/analyzing/$id'
      preLoaderRoute: typeof AnalyzingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRoute: UploadRoute,
  AnalyzingIdRoute: AnalyzingIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  PaywallIdRoute: PaywallIdRoute,
  ReportIdRoute: ReportIdRoute,
  ResultsIdRoute: ResultsIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
